import "../config/gsap-config.js";
import { LenisSmooth } from "../config/scrollsmooth.js";
import { ActiveLinks } from "../components/active-links.js";
import { Navbar } from "../components/navbar.js";
import { CustomSwiper } from "../components/global-swiper.js";
import { HomepageAnimations } from "../animations/homepage.js";
import { SharedAnimations } from "../animations/shared-animations.js";
import { Accordion } from "../components/accordion.js";
import { Toggles } from "../components/toggles.js";
import { CryptoData } from "../components/crypto-data.js";
import { initDetectScrollingDirection } from "../utils/detect-scroll-direction.js";
import { VimeoBGVideo } from "../utils/vimeo-bg-video.js";
import { Newsletter } from "../components/newsletter.js";
import { CryptoSwap } from "../components/crypto-swap.js";

window.addEventListener("DOMContentLoaded", async () => {
  new Newsletter();
  const lenis = new LenisSmooth();
  initDetectScrollingDirection();
  new ActiveLinks();
  new Navbar();
  new CustomSwiper();
  new HomepageAnimations(lenis);
  new SharedAnimations();
  new Accordion();
  new Toggles(lenis);
  new VimeoBGVideo(lenis);
  const cryptoData = await new CryptoData().init();
  new CryptoSwap(cryptoData);
});
